apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: conote

resources:
  - kong-postgres.yaml
  - kong-migration.yaml
  - kong.yaml
  - kong-config.yaml
  - kong-configure.yaml

commonLabels:
  app.kubernetes.io/name: kong-gateway
  app.kubernetes.io/managed-by: kustomize
