apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: conote

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - elasticsearch.yaml
  - backend-config.yaml
  - backend.yaml

commonLabels:
  app.kubernetes.io/name: conote
  app.kubernetes.io/managed-by: kustomize
